service: serverless-node-js-app

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: any
          cors: true
      - htpp: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
